# Generated by Django 6.0.6 on 2026-06-23 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de equipo',
                'verbose_name_plural': 'Categorías de equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del equipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción técnica')),
                ('banda_frecuencia', models.CharField(choices=[('libre', 'Banda libre (2.4 / 5.7 GHz)'), ('restringida', 'Frecuencia restringida'), ('no_aplica', 'No aplica')], default='no_aplica', max_length=20, verbose_name='Banda de frecuencia')),
                ('requiere_permiso', models.BooleanField(default=True, verbose_name='Requiere permiso de importación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo en catálogo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='equipos.categoriaequipo', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
                'unique_together': {('marca', 'modelo')},
            },
        ),
    ]
