# Generated by Django 6.0.6 on 2026-09-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('persona_natural', 'Persona Natural'), ('especialista_radiofaro', 'Especialista Radiofaro'), ('especialista_movil', 'Especialista Móvil'), ('especialista_maritimo', 'Especialista Marítimo'), ('especialista_internet', 'Especialista Internet'), ('especialista_superior', 'Especialista Superior'), ('aduana', 'Aduana'), ('directivo', 'Directivo')], default='persona_natural', max_length=30, verbose_name='Rol'),
        ),
    ]
