# Generated by Django 6.0.6 on 2026-06-23 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de solicitud')),
                ('flujo', models.CharField(choices=[('f43', 'F43 — Solicitud previa a importación'), ('rats', 'RATS — Equipo retenido en aduana')], max_length=10, verbose_name='Tipo de flujo')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('en_revision', 'En revisión'), ('aprobada', 'Aprobada'), ('denegada', 'Denegada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('equipo_no_listado', models.BooleanField(default=False, verbose_name='Equipo no listado en catálogo')),
                ('equipo_descripcion', models.TextField(blank=True, verbose_name='Descripción del equipo (no listado)')),
                ('equipo_marca_manual', models.CharField(blank=True, max_length=100, verbose_name='Marca (manual)')),
                ('equipo_modelo_manual', models.CharField(blank=True, max_length=100, verbose_name='Modelo (manual)')),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to='solicitudes/documentos/%Y/%m/', verbose_name='Documento adjunto')),
                ('numero_rats', models.CharField(blank=True, max_length=50, verbose_name='Número RATS')),
                ('fecha_retencion', models.DateField(blank=True, null=True, verbose_name='Fecha de retención')),
                ('observaciones_solicitante', models.TextField(blank=True, verbose_name='Observaciones del solicitante')),
                ('observaciones_operador', models.TextField(blank=True, verbose_name='Observaciones del operador')),
                ('observaciones_tecnicas', models.TextField(blank=True, verbose_name='Criterio técnico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='equipos.equipo', verbose_name='Equipo')),
                ('operador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Operador asignado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
