# Generated by Django 6.0.6 on 2026-07-13 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_historialsolicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_revision_directivo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión directiva'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='revisada_directivo',
            field=models.BooleanField(default=False, verbose_name='Revisada por dirección'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='revisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_supervisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisada por'),
        ),
    ]
