# Generated by Django 6.0.6 on 2026-09-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_solicitud_fecha_revision_directivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='categoria',
            field=models.CharField(blank=True, choices=[('radiofaro', 'Radiofaro'), ('movil', 'Móvil'), ('maritimo', 'Marítimo'), ('internet', 'Internet')], max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('en_revision', 'En revisión'), ('en_revision_superior', 'En revisión superior'), ('pendiente_aprobacion', 'Pendiente de aprobación'), ('pendiente_pago', 'Pendiente de pago'), ('aprobada', 'Aprobada'), ('denegada', 'Denegada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
    ]
