# Generated by Django 6.0.6 on 2026-06-26 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0002_historialsolicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Número de licencia')),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('vencida', 'Vencida'), ('revocada', 'Revocada')], default='vigente', max_length=20, verbose_name='Estado')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('motivo_revocacion', models.TextField(blank=True, verbose_name='Motivo de revocación')),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revocación')),
                ('emitida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licencias_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Emitida por')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='licencia', to='solicitudes.solicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
