# Generated by Django 6.0.6 on 2026-09-25 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0001_initial'),
        ('solicitudes', '0004_solicitud_categoria_alter_solicitud_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Número de factura')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuesto')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('emitida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Emitida por')),
                ('registrado_pago_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Pago registrado por')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='solicitudes.solicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
